version: '3.8'
 
services:
  dtrack-apiserver:
    image: dependencytrack/apiserver
    deploy:
      resources:
        limits:
          memory: 3072m
        reservations:
          memory: 1024m
    ports:
      - "8080:8080"
    volumes:
      - "dtrack-volume:/data"
    restart: unless-stopped
 
  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    ports:
      - "80:8080"
    restart: unless-stopped
 
volumes:
  dtrack-volume:
